---
- name: "roles/common/tasks/sysctl: Disable ipv6"
  become_user: root
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: "net.ipv6.conf.all.disable_ipv6"
      value: 1
    - name: "net.ipv6.conf.default.disable_ipv6"
      value: 1

