---
- name: "roles/langs.php/tasks/main: Install PHP 8.0.9 from xbuild"
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon
  command: >
    /tmp/xbuild/php-install 8.0.9 /home/isucon/local/php --
    --with-pcre-regex --with-zlib --enable-fpm --enable-pdo --with-pear
    --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl
    --with-pcre-regex --with-pcre-dir --with-libxml-dir --enable-opcache
    --enable-bcmath --with-bz2 --enable-calendar --enable-cli --enable-shmop
    --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-mbregex
    --enable-mbstring --enable-pcntl --enable-sockets --with-curl --enable-zip
  environment:
    PHP_BUILD_EXTRA_MAKE_ARGUMENTS: "-j {{ ansible_processor_vcpus }}"

- name: "roles/langs.php/tasks/main: Add PATH for PHP"
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK php"
    dest: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/php/bin:$PATH
