---
- name: "roles/bench.supervisor/tasks/generate_env: Deploy generate-env.sh"
  tags:
    - aws
  become_user: root
  copy:
    src: "var/lib/cloud/scripts/per-instance/generate-env_aws.sh"
    dest: "/var/lib/cloud/scripts/per-instance/generate-env.sh"
    owner: "root"
    group: "root"
    mode: "0755"
