---
- name: "common roles"
  hosts: all
  tags:
    - contestant
    - bench
    - standalone
  become: true
  roles:
    - common
    - langs

- name: "contestant roles"
  hosts: [contestant, standalone]
  tags: [contestant, standalone]
  become: true
  roles:
    - langs.go
    - langs.nodejs
    - langs.php
    - langs.python
    - langs.ruby
    - langs.rust
    - contestant

- name: "bench roles"
  hosts: [bench]
  tags: [bench]
  become: true
  roles:
    - langs.go
    - langs.rust
    - bench
    - bench.node_exporter
    - bench.supervisor

- name: "bench (standalone) roles"
  hosts: [standalone]
  tags: [standalone]
  become: true
  roles:
    - bench

