---
- name: "roles/langs.ruby/tasks/main: Install Ruby v3.0.2 from xbuild"
  become: yes
  become_user: isucon
  command: /tmp/xbuild/ruby-install 3.0.2 /home/isucon/local/ruby

- name: "roles/langs.ruby/tasks/main: Add PATH for Ruby"
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Ruby"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/ruby/bin:$PATH

