name: ci for go
on:
  push:
    branches: [ main ]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/**/*
      - .github/workflows/go.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/**/*
      - .github/workflows/go.yml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./webapp/go
          args: "-c ../../.github/.golangci.yml"
  test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Go App
        run: target=go docker-compose -f docker-compose-ci.yml up -d --build -- backend mysql-backend
        working-directory: development
      - name: Test Go App
        run: docker-compose -f docker-compose-ci.yml up --exit-code-from apitest -- apitest
        working-directory: development
