name: ci for go
on:
  push:
    branches: [ main ]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-ci.yml
      - development/docker-compose-dev.yml
      - development/Makefile
      - .github/workflows/go.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-ci.yml
      - development/docker-compose-dev.yml
      - development/Makefile
      - .github/workflows/go.yml

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./webapp/go
          args: "-c ../../.github/.golangci.yml"
  test:
    name: Integration Test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: development
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install some utils
        env:
          AWS_CLI_VERSION: 2.2.16
        run: |
          curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip -o /tmp/awscliv2.zip \
            && unzip -o /tmp/awscliv2.zip -d /tmp/ \
            && /tmp/aws/install --update -i $HOME/work/_tool/isucon11-qualify/aws-cli -b $HOME/work/_tool/isucon11-qualify


      - name: Download init-data.sql
        working-directory: webapp/sql
        run: ${HOME}/work/_tool/isucon11-qualify/aws s3 cp s3://isucon11-qualify-dev/initial-data.sql ./1_InitData.sql

      - name: Build Go App
        run: target=go docker-compose -f docker-compose-ci.yml up -d --build -- backend mysql-backend
      - name: Test Go App
        run: |
          # イメージを self-hosted runner のローカルからコピー
          rm -r ../bench/images && cp -a /opt/isucon11-qualify/images ../bench/images
          target=go docker-compose -f docker-compose-ci.yml up --build --exit-code-from apitest -- apitest
      - name: Clean up
        if: failure() || true
        run: target=go docker-compose -f docker-compose-ci.yml down
